import timg1 from '/public/images/team/img-1.jpg'
import timg2 from '/public/images/team/nb.png'
import timg3 from '/public/images/team/img-3.jpg'
import timg4 from '/public/images/team/img-4.jpg'

const Teams = [
    {
        Id: '1',
        tImg: timg1,
        name: 'Melissa Sutherland',
        slug: 'Melissa-Sutherland',
        title: 'Founder',
        phone: '654-54851-5447',
        email: 'necterbuddy@hotmail.com',
        experience: '11 Years',
        address: '45 Big Fella Street, Sweet Home, Bela',
        about: 'Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather.',
        experienceDetails: 'Above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.',
        education: 'Above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.',
        achievements: [
            'Best Lawyer Award 2017',
            'Won 100 Cases in 2018',
            'Special Award for Family Law Activity 2018',
            'Super Lawyers’ Top 50 Lawyers in USA',
        ],
        skills: [
            { skill: 'Business', percentage: '85%' },
            { skill: 'Consulting', percentage: '95%' },
            { skill: 'Marketing', percentage: '92%' },
            { skill: 'Bankruptcy', percentage: '95%' },
        ],
        socialLinks: {
            facebook: '#',
            twitter: '#',
            linkedin: '#',
            pinterest: '#',
            instagram: '#',
        },
    },
    {
        Id: '2',
        tImg: timg1,
        name: 'Nicholas Buscemi',
        slug: 'Nicholas-Buscemi',
        title: 'Lead Developer',
        phone: '631-316-5618',
        email: 'nbuscemi@wynstrategies.com',
        experience: '4 Years',
        address: '',
        about: 'Samsa was a travelling salesman...',
        experienceDetails: 'Above it there hung a picture...',
        education: 'Above it there hung a picture...',
        achievements: ['Best Developer 2020', 'Built 10+ Scalable Apps'],
        skills: [
            { skill: 'Web Development', percentage: '95%' },
            { skill: 'React.js', percentage: '90%' },
            { skill: 'Node.js', percentage: '88%' },
            { skill: 'Database Design', percentage: '85%' },
        ],
        socialLinks: {
            facebook: '#',
            twitter: '#',
            linkedin: '#',
            pinterest: '#',
            instagram: '#',
        },
    },
    {
        Id: '3',
        tImg: timg3,
        name: 'Carolann Yazzo',
        slug: 'Carolann-Yazzo',
        title: 'Medical Consultant',
        phone: '654-54851-5447',
        email: 'necterbuddy@hotmail.com',
        experience: '11 Years',
        address: '45 Big Fella Street, Sweet Home, Bela',
        about: 'Samsa was a travelling salesman...',
        experienceDetails: 'Above it there hung a picture...',
        education: 'Above it there hung a picture...',
        achievements: ['Medical Excellence Award 2019', 'Certified Health Consultant'],
        skills: [
            { skill: 'Healthcare Management', percentage: '90%' },
            { skill: 'Consulting', percentage: '95%' },
        ],
        socialLinks: {
            facebook: '#',
            twitter: '#',
            linkedin: '#',
            pinterest: '#',
            instagram: '#',
        },
    },
    {
        Id: '4',
        tImg: timg4,
        name: 'Takao Mangulis',
        slug: 'Takao-Mangulis',
        title: 'Contract Consultant',
        phone: '654-54851-5447',
        email: 'necterbuddy@hotmail.com',
        experience: '11 Years',
        address: '45 Big Fella Street, Sweet Home, Bela',
        about: 'Samsa was a travelling salesman...',
        experienceDetails: 'Above it there hung a picture...',
        education: 'Above it there hung a picture...',
        achievements: ['Contract Excellence Award 2020', 'Negotiated $10M+ Deals'],
        skills: [
            { skill: 'Legal Consulting', percentage: '95%' },
            { skill: 'Contract Negotiation', percentage: '92%' },
        ],
        socialLinks: {
            facebook: '#',
            twitter: '#',
            linkedin: '#',
            pinterest: '#',
            instagram: '#',
        },
    },
];

export default Teams;
